# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/deploy-')) ||
      (github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'tag release'))
      
    steps:
      - name: Git Checkout 
        uses: actions/checkout@v1
        
      - name: Checkout Master
        run: git checkout master
        
      - name: Logging first time
        run: |
            ls
            pwd  
      - name: Change Directory
        run: cd packages
        
      - name: Logging second time
        run: |
            ls
            pwd
        
      - name: testing
        run: |
            echo "${{ github.event.head_commit.message }}"
            echo "${{ github.event_name }}"
            echo "${{ github.ref }}"
            echo "${{ github.event_name	 }}"
            echo "${{ github.sha }}"
            echo "${{ github.head_ref }}"
            echo "${{ github.base_ref }}"

      - name: Install Packages
        run: npm i

      - name: Config Github Credentials
        run: |
          git config --global url."https://${{secrets.GITHUB_CI_TOKEN}}:@github.com/".insteadOf "https://github.com/"
          git config --global user.email "fmontadamt@gmail.com"
          git config --global user.name "CI"

      - name: Version
        run: |
          git stash
          npm run version

#     - name: Test
#       run: echo test-version

#     - run: echo testing-trigger
#       env:
#         CI: true
